void initialise();
void initcoordsvel();
void initvel(int *);
void initarrays();
void initeventlist();
void singleEvent();
void nextevent();
void predictevent(int ,int);
void scheduleEvent();
void collision();
void cellcrossing();
void deletenode(int);
void clearclist(int);
void energycal();
void updatemol();
void updatesystem();
void checkoverlap(int *,int *,double *);
void checkoverlap2(int *);
void printoutput();
void properties();
void configuration();
